name: $bog_wysiwyg_app

permissions: write-all

on:
    workflow_dispatch:
    push:
    pull_request:
    delete:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: hyoo-ru/mam_build@master2
              with:
                  package: "bog/wysiwyg"
                  modules: 'app'


            - uses: hyoo-ru/gh-deploy@v4.4.1
              if: github.ref == 'refs/heads/main'
              with:
                  folder: "bog/wysiwyg/app/-"

